# Stage 1: Build the binary
FROM golang:1.22.5

# Install build dependencies
RUN apt-get update && \
    apt-get install -y \
    git \
    curl \
    redis-tools && \
    apt-get clean

# Set working directory
WORKDIR /app

# Cache dependencies for faster rebuilds
COPY go.mod go.sum ./
RUN go mod tidy && \
    go mod vendor

# Copy source code and build the app
COPY . .
RUN mkdir -p /var/db && \
    mv docker/dev-configs/* /var/db/ && \
    mv docker/scripts/init-keyhouse /usr/local/bin/ && \
    go build -o keyhouse ./cmd/main.go

# Copy Swagger UI static files (assumes `swagger-ui` is in your project root)
COPY swagger-ui /app/swagger-ui

# Run the binary
CMD ["/app/keyhouse"]
